name: f_abm_env
dependencies:
  - python>3.9
  - pip>23.0
  - pip:
    - matplotlib>3.5
    - numpy>1.20
    - pytest==7.2.2
    - igraph==0.10.4
    - pandas>1.3
    - openpyxl==3.1.2
    - pycairo>=1.20
