name: automatic_sphinx_doc
run-name: Creating documentation using Sphinx
on: [push]
jobs:
  update-sphinx-documentation:
    runs-on: ubuntu-latest
    steps:
      - run: pip install sphinx
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -la
      - run: sphinx-apidoc -o ./docs ./src/
      - run: cd docs
      - run: make clean html
