name: automatic_sphinx_doc
run-name: Creating documentation using Sphinx
on: [push]
jobs:
  update-sphinx-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --from=markdown 
            --to=rst 
            --output=docs/CONTRIBUTING.rst 
            CONTRIBUTING.md
      - run: | 
          pip install sphinx
          pip install sphinx_rtd_theme
          pip install myst-parser
          pip install -r requirements.txt
      - run: |
          pwd
          ls -la
          rm docs/src.rst
          rm docs/modules.rst
          sphinx-apidoc -o ./docs ./src/
          cd docs
          pwd
          ls -la
          make clean html
